### ISSUE TITLE
No ability to change I2C bus used

### ISSUE THREAD

**Issue by omorgan831** [iiot2k/node-red-contrib-iiot-rpi-pcf857x#2]
Pi has options for a few i2c buses, the one used most as an alternative is i2c0 (GPIO0 and GPIO1 - pins 27 and 28 on the 40pin GPIO).

It seems the i2c bus selection is embedded into the binary blob .node file in /lib (unless my code reading is even worse than I thought!)

Is there a way to edit to allow selection between i2c1 (the default) and another i2c bus on the pi (in this case i2c0).

Do you have the source for the binary blob so we could edit ourselves?

There is only this node and 1 other that are targeted at the PCF8575 and the generic i2c nodes are not the easiest to wrangle. So any help would be a huge benefit.

Thanks in advance.

**Comment by iiot2k** [comment]
The second i2c port is intended for special hardware on the Raspberry pi. 
The second port cannot be enabled with raspi-config either. 
The .node driver is written in C++ and needs to be compiled again if it changes.
What is your reason for not using the standard i2c port?

**Comment by omorgan831** [comment]
I wouldn't say its too 'special' its been an alt function of GPIO01 and 2 for a very very long time and whilst it does require a line in /boot/config.txt its not that uncommon. Porting the likes of the other 'hidden' i2c busses that are part of the internal mux would definitely be more oddball.


My use is that I have a small hat that covers GPIO pins 1 - 10 on the header so need to use the alt i2c0 for my needs.

Another use case is of course the more annoying case of sensor modules with hardwired addresses and wanting more than 1 without adding an i2c expander.

I do understand the .node file is precompiled (didn't know it was from C++). An option might be to just make the source for the c++ avaliable and then I can compile a new version myself?

If there is a way (like some of the i2c node-red modules to have a field for i2c device) that would be even more amazing, but appreciate time to dev that is likely not readily avaliable (although if you did open the C++ source I might fork and add that if I have time).

Owen.

**Comment by omorgan831** [comment]
If you are willing to provide the C++ for the .node binary I'm more than willing to fork and do the work and maybe if I'm able to get it to where its something changeable from the nodered ui I could submit a merge request.

I'm happy to do the work, just need a leg up on the source behind the binary.

**Comment by iiot2k** [comment]
Hi Owen,
Normally I don't want to publish the C++ source files here. 
The reason is not the source files, but you need a special build environment and project settings.
You must install the Raspberry Pi 32bit and 64bit compiler on the PC.
Can you send me your email address to iiot2k@gmail.com ?
